### PR TITLE
174 no carbs on badge

### PR DESCRIPTION
**Pull request by bjornoleh**
Just a test to of doing a pull request with my modification of LoopDataManager.swift to avoid the Time zone bug.

Modified release 174: Removed changes from "Show required carbs in app badge" https://github.com/ivalkou/Loop/commit/21396d3965c64d3fa93cf09718d2f8635d0c4703 in Loop/Managers/LoopDataManager.swift.

### CODE REVIEW

**Comment by Jon-b-m** [comment]
> Just a test to of doing a pull request with my modification of LoopDataManager.swift to avoid the Time zone bug.
> 
> Modified release 174: Removed changes from "Show required carbs in app badge" [ivalkou@21396d3](https://github.com/ivalkou/Loop/commit/21396d3965c64d3fa93cf09718d2f8635d0c4703) in Loop/Managers/LoopDataManager.swift.

Thanks Bjørn Ole, I'm not sure however about the first commit (https://github.com/Jon-b-m/Loop/pull/9/commits/a109c75747b74c36c0cfddfb67fd017387972175). I can't see that the actual toggle is removed, seems like you maybe deleted some other part instead? ¯\_(ツ)_/¯

**Comment by bjornoleh** [comment]
Hi, it seems I made some kind of a mess with this pull request. I should remove the last change to the PR.

I have made some attempts to remove the toggle, but they all ended in failed builds in Xcode. Too many things are depending on the next couple of commits in the main FreeAPS branch, so I am going to leave that for now.

But during my testing, I learned a bit more git :-)

The easiest way to revert specific prior changes is to `git revert <commit_ID>`. This will gve a new commit, which have to be committed and pushed to your Github repository (or keep it in the local clone only).

So in this case, to revert the "Show required carbs in app badge" feature, simply 
`git revert 21396d3965c64d3fa93cf09718d2f8635d0c4703`

**Comment by Jon-b-m** [comment]
I think perhaps the easiest way of removing the toggle, and not mess up some other code,  is just commentating out three lines that I have marked: 
A5C708F6-F0F2-4A3C-A607-901B0FB479EE_1_105_c

**Comment by Jon-b-m** [comment]
The earlier commit that I suggested to remove in Telegram is not there anymore, it's an old commit not in 174, so maybe that's why you accidentally deleted some other commit instead?

**Comment by bjornoleh** [comment]
No, I removed the code that you suggested, see how there is a minus sign (-) in front of every line in my commit, and a plus (+) in the original commet? I essentially deleted every line of that file.

This is the cithub vcommit compared toour discussion in Telegram, hopefully we are talking about the same thing ;-) 
image

**Comment by Jon-b-m** [comment]
It's a bit confusing, because the commit I was referring to isn't there anymore in the 174 version, but maybe I'm seeing this backwards? Now in version 174, the **only** code that needs editing is the three lines I marked in image above. That is in that particular file, the FreeAPSSettingsViewController, I think 🤔 😊

**Comment by Jon-b-m** [comment]
The lines you deleted are supposed to be still there in version 174. They don't need to be removed and maybe shouldn't either. This is screenshot of current 174 in Xcode and the deleted files in your commit to the left:

**Comment by Jon-b-m** [comment]
CC6F8D0E-A8BF-455A-9540-FA78562D63A1_1_105_c

**Comment by Jon-b-m** [comment]
These lines have nothing to do with the AppBadge

**Comment by bjornoleh** [comment]
Ok, I did a number of things, and started reverting some of the next commits as well to see if I could resolve som ebuild errors. I eventually gave up on this, and determined that I was happy with just reverting the "Show required carbs in app badge" feature, which edits a single file, and does not seem to cause any harm :-)

As mentined above:
git revert 21396d3965c64d3fa93cf09718d2f8635d0c4703

I think the best option now is to simply close/reject this PR and move on :-)

**Comment by Jon-b-m** [comment]
Yep! I will make an own attempt of this. I have made a new branch "NoAppBadge". Will push changes to this branch later. Thanks

**Pull request closed without merging**
